### ISSUE TITLE
Incorrect puzzle completion display

### ISSUE THREAD

**Issue by tkaragianes** [eternagame/eterna-mobile#32]
"Okay, so I noticed a potential bug. The website (correctly) shows I completed a particular puzzle (The First Eterna3D puzzle) but the mobile app does not. In fact, the mobile app does not seem to acknowledge any of the non-tutorial puzzles that I have completed on the website, either with a checkmark on the thumbnail or through the filter option on the puzzles."

"Also doesn't acknowledge it on the puzzle description. But when I enter the puzzle, it correctly shows me the >>> to show the finish screen. Clicking this >>> does not change the previously described screens to show I completed the puzzle"

**Comment by luxaritas** [comment]
There's two things going on here:
1) Puzzle cards don't show a checkmark or any other completion indicator, nor does the puzzle info page
2) The filter doesn't work. This is because apparently the notcleared API parameter isn't determining the user to filter cleared status by from the currently logged in user - you have to provide a uid parameter with the user ID of the user you want to use for the cleared status
