### ISSUE TITLE
Weird bug regarding design constraints for a lab - doesn't show "violations constraint" on mobile only

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#86]
The "violations constraint" for the current MiniPTC lab doesn't show on mobile, but does show on desktop. All of the other constraints for this lab do show up correctly. I would also like to note that even though the actual constraint doesn't show up on mobile, the outline of that box is red (indicating it isn't satisfied) instead of green (which would indicate it is satisfied), even when I reset the puzzle and it should start out as "green" because no changes have been made (which is the behavior on desktop). Screenshots below:

On mobile:

![pic1](https://user-images.githubusercontent.com/35237235/159765177-56c7617c-89c9-40e6-9312-e8415417957a.PNG)

![pic2](https://user-images.githubusercontent.com/35237235/159765196-d53b2a7e-be03-43a4-8b01-537da70f680d.png)

On desktop:

![pic3](https://user-images.githubusercontent.com/35237235/159765213-8e68d66f-16f2-4850-8316-63bb289eae7f.png)

![pic4](https://user-images.githubusercontent.com/35237235/159765233-f8ed3cd0-6196-4934-8fc1-16029aac587c.png)

This issue does not seem specific to the MiniPTC lab - for example, see this mobile screenshot from one of the OpenVaccine labs:

![pic5](https://user-images.githubusercontent.com/35237235/159766416-39dbfa82-038f-4a40-a838-515a87c64ed8.png)

**Comment by luxaritas** [comment]
The constraint script 9606956 was crashing because it fetches the puzzle info from the API by finding the puzzle ID in the URL, but it was grabbing part of the mobile app URL that wasn't the actual puzzle ID. I've resolved the issue for this script by changing:
```
href.match(/\d{6,}/)[0];
```
(or something like that, I didn't write down the exact original expression) to
```
href.match(/(Application\/[^\/]+\/)?[^\d]+(\d{6,})/)[2];
```

We'll have to keep an eye out if this presents an issue with other scripted constraints.
